### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Judeanumudu1**
$CASH Logo

### CODE REVIEW

**Comment by fexcash** [comment]
Any clearer pictures?

**Comment by fexcash** [comment]
please follow the readme instructions to submit

**Comment by Judeanumudu1** [comment]
Yes, I followed the instructions very well and implemented everything
Here is another picture.
CASH LOGO2

**Comment by fexcash** [comment]
1. You should put the new image in your commit.
2. the file name should be {token-id}.png, like `48ecdb39f9961c22a04662eb72c0b8b9078083b5dd6a025bd581a5df9ae2eb82.png`

**Comment by Judeanumudu1** [comment]
Okay. thank you
One more problem I have is that if I make it 16*16 as stated on the readme instructions it becomes tinier like the former one you saw, before requesting a clearer one. So, I will go ahead and upload this one this way without the resize. The resize makes the logo look blurred.

The new logo has been committed now. pls, approve. thank you

**Review by Judeanumudu1 — COMMENTED** [review]
token id png

**Comment by fexcash** [comment]
I've merged it first, I'll edit it for you

**Comment by Judeanumudu1** [comment]
Thank you so much for being helpful and for the prompt response. I am not taking it for granted. Thanks for the help again, I will do it soon.

**Comment by Judeanumudu1** [comment]
Are you yet to update it on your public repo, I cannot find the logo on fex-cash/fex-assets/logo

**Pull request merged**
