### PR TITLE
Update bcmr.json

### PR DESCRIPTION
**Pull request by BiWinBi**
I changed the name of BWB into BWBT on #BCMR
so it won't be confused with BWB on #CRC20

Here is the #BCMR json file
https://gist.github.com/BiWinBi/16a92d06305a727674a1131379dfd4e9
And the BWBT on salemkode explorer
https://explorer.salemkode.com/token/36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797

Thank you very much

### CODE REVIEW

**Comment by fexcash** [comment]
Why are there two BWBTs?

**Comment by BiWinBi** [comment]
Sorry, the second one doesn't exist anymore
You can just delete it
There is only one BWBT [36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797](https://explorer.salemkode.com/token/36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797) in use now
Thank you very much

**Comment by BiWinBi** [comment]
Screenshot_2023-08-04-16-58-34-388_com android chrome

The second one was created at the exactly same second as the first one
I used Cashonize to create the first one
Maybe Cashonize created the second one 
That's a mystery to me

**Comment by fexcash** [comment]
I can't modify your branch directly, you can update it.

**Comment by BiWinBi** [comment]
Sure, thanks a lot @fexcash

**Comment by BiWinBi** [comment]
It's already BWBT on AuthChain now
For example:
https://tokenstork.com

**Pull request merged**
